services:

    _defaults:
        autowire: true
        autoconfigure: true


    Tastaturberuf\ContaoImageCopyrightBundle\DataContainer\ModuleDataContainer: ~

    Tastaturberuf\ContaoImageCopyrightBundle\DataContainer\FilesDataContainer:
        arguments:
            $validImageExtensions: '%contao.image.valid_extensions%'


    Tastaturberuf\ContaoImageCopyrightBundle\Controller\ImageCopyrightListController:
        arguments:
            $rootDir: '%kernel.project_dir%'
            $validImageExtensions: '%contao.image.valid_extensions%'

    Tastaturberuf\ContaoImageCopyrightBundle\EventListener\AddCopyrightFieldsToImageTemplateListener:
        arguments:
            - '@contao.routing.scope_matcher'
            - '@request_stack'
